[package]
name = "pufu"
version = "0.1.0"
edition.workspace = true
description = "A simple in-memory serialization/deserialization library"
license.workspace = true

[dependencies]
pufu-core = { path = "../core" }
pufu-macros = { path = "../macros" }
