[package]
name = "pufu-core"
version = "0.1.2"
edition.workspace = true
description = "Core for the pufu in-memory serialization/deserialization library"
license.workspace = true
readme = "../README.md"

[dev-dependencies]
hex = "0.4"
