[package]
name = "pufu-core"
version.workspace = true
edition.workspace = true
description = "Core library for pufu"

[dependencies]
pufu-macros = { path = "../macros" }

[[example]]
name = "encode_encode_expand"
path = "examples/encode_encode_expand.rs"
